# Numpy Practice

#### Practice Exerxise from
https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/numpy-exercises.ipynb

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[2,3,4],
             [5,6,7]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[8,9,10],
                [10,11,12],
                [13,14,15]],
               [[1,2,3],
                [4,5,6],
                [7,8,9]]])

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [7]:
df1 = pd.DataFrame(a2)
df1

0  1  2
0  2  3  4
1  5  6  7

In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
array_1 = np.arange(0,100,3)
array_1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size = (7,2))
random_array

array([[3, 5],
       [8, 3],
       [9, 7],
       [8, 7],
       [8, 6],
       [3, 0],
       [7, 8]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.random((3,5))
random_float_array

array([[0.24751128, 0.82090632, 0.06514978, 0.95350933, 0.30813576],
       [0.74464412, 0.19330218, 0.10901254, 0.13513885, 0.28816768],
       [0.54898067, 0.43982182, 0.77701058, 0.05529667, 0.36388109]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_seed = np.random.randint(10, size = (4,6))
random_array_seed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_1 = np.random.randint(10, size = (3,7))
random_array_1
# Find the unique numbers in the array you just created
np.unique(random_array_1)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [15]:
random_array_1

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [16]:
# Find the 0'th index of the latest array you created
random_array_1[0]

array([8, 0, 9, 2, 6, 3, 8])

In [59]:
# Get the first 2 rows of latest array you created
random_array_1[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [60]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_1[:2,:2]

array([[8, 0],
       [2, 4]])

In [19]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(10, size = (3,5))
random_ones = np.ones((3,5))

In [20]:
random_array

array([[4, 1, 3, 6, 7],
       [2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9]])

In [21]:
random_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Add the two arrays together
sum_array = sum(random_array, random_ones)
sum_array

array([[10.,  3., 12., 13., 24.],
       [10.,  3., 12., 13., 24.],
       [10.,  3., 12., 13., 24.]])

In [23]:
# Create another array of ones of shape (5, 3)
random_ones_ones = np.ones((5,3))
random_ones_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# Try add the array of ones and the other most recent array together
sum_array_2 = random_array + random_ones_ones.T
sum_array_2

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [25]:
# Create another array of ones of shape (3, 5)
random_array_3 = np.ones((3,5))
random_array_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# Subtract the new array of ones from the other most recent array
subs = sum_array_2 - random_array_3
subs

array([[4., 1., 3., 6., 7.],
       [2., 0., 3., 1., 7.],
       [3., 1., 5., 5., 9.]])

In [27]:
# Multiply the ones array with the latest array
multi = subs * random_array_3
multi

array([[4., 1., 3., 6., 7.],
       [2., 0., 3., 1., 7.],
       [3., 1., 5., 5., 9.]])

In [28]:
# Take the latest array to the power of 2 using '**'
power_array = multi **2
power_array

array([[16.,  1.,  9., 36., 49.],
       [ 4.,  0.,  9.,  1., 49.],
       [ 9.,  1., 25., 25., 81.]])

In [29]:
# Do the same thing with np.square()
power_array = np.square(multi)
power_array

array([[16.,  1.,  9., 36., 49.],
       [ 4.,  0.,  9.,  1., 49.],
       [ 9.,  1., 25., 25., 81.]])

In [30]:
# Find the mean of the latest array using np.mean()
mean_array = np.mean(power_array)
mean_array

21.0

In [31]:
# Find the maximum of the latest array using np.max()
max_array = np.max(power_array)
max_array

81.0

In [32]:
# Find the minimum of the latest array using np.min()
min_array = np.min(power_array)
min_array

0.0

In [33]:
# Find the standard deviation of the latest array
std_array = np.std(power_array)
std_array

22.82104292095346

In [34]:
# Find the variance of the latest array
var_array = np.var(power_array)
var_array

520.8

In [35]:
# Reshape the latest array to (3, 5, 1)
power_reshape = power_array.reshape(3,5,1)
power_reshape

array([[[16.],
        [ 1.],
        [ 9.],
        [36.],
        [49.]],

       [[ 4.],
        [ 0.],
        [ 9.],
        [ 1.],
        [49.]],

       [[ 9.],
        [ 1.],
        [25.],
        [25.],
        [81.]]])

In [36]:
# Transpose the latest array
power_trans = power_reshape.T
power_trans

array([[[16.,  4.,  9.],
        [ 1.,  0.,  1.],
        [ 9.,  9., 25.],
        [36.,  1., 25.],
        [49., 49., 81.]]])

In [37]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1 = np.random.randint(10, size = (3,3))
a2 = np.random.randint(10, size = (3,2))

In [38]:
dot_arrays = np.dot(a1, a2)
dot_arrays

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [39]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a3 = np.random.randint(10, size = (4,3))
a4 = np.random.randint(10, size = (4,3))

In [41]:
# Perform a dot product on the two newest arrays you created
#dot_arrays_2 = np.dot (a3, a4)

#It doesn't work. How would you fix it?

# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

dot_arrays_2 = np.dot(a3, a4.T)
dot_arrays_2

array([[ 72,  50, 201, 184],
       [ 68,  24, 102,  96],
       [ 49,  16, 114, 106],
       [ 53,  22, 123, 114]])

In [43]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
#trans_prod = a3.T * a4
#trans_prod
#ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 


In [44]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a5 = np.random.randint(10, size = (5,4))
a6 = np.random.randint(10, size = (5,4))

In [45]:
# Compare the two arrays with '>'
a5 > a6

array([[False, False, False,  True],
       [False,  True,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [46]:
# Compare the two arrays with '>='
a5 >= a6

array([[False, False, False,  True],
       [ True,  True,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [47]:
# Find which elements of the first array are greater than 7
a5 > 7

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [48]:
# Which parts of each array are equal? (try using '==')
a5 == a6

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [49]:
# Sort one of the arrays you just created in ascending order
a5_sorted = np.sort(a5)
a5_sorted

array([[0, 1, 6, 7],
       [2, 4, 6, 7],
       [0, 2, 5, 7],
       [0, 2, 2, 4],
       [4, 6, 6, 9]])

In [50]:
# Sort the indexes of one of the arrays you just created
a6_index_sort = np.argsort(a6)
a6_index_sort

array([[3, 0, 1, 2],
       [1, 2, 3, 0],
       [3, 0, 1, 2],
       [3, 1, 2, 0],
       [2, 3, 1, 0]], dtype=int64)

In [51]:
# Find the index with the maximum value in one of the arrays you've created
a6_index_max = np.argmax(a6)
a6_index_max

1

In [52]:
# Find the index with the minimum value in one of the arrays you've created
a5_index_min = np.argmin(a5)
a5_index_min

2

In [53]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
a5_index_max_axis_1 = np.argmax(a5, axis = 1)
a5_index_max_axis_1

array([0, 1, 0, 1, 1], dtype=int64)

In [54]:
a5

array([[7, 1, 0, 6],
       [6, 7, 4, 2],
       [7, 5, 2, 0],
       [2, 4, 2, 0],
       [4, 9, 6, 6]])

In [55]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
a6_index_min_axis_0 = np.argmin(a6, axis = 0)
a6_index_min_axis_0

array([2, 1, 1, 3], dtype=int64)

In [61]:
# Create an array of normally distributed random numbers
randomly = np.random.randn(3,5)
randomly

array([[-0.90698723, -0.81735416, -0.48312268, -0.56982835, -2.09159967],
       [ 1.26374053, -0.01548334, -0.02737645,  0.81787351, -1.05460447],
       [-0.75832712,  0.45741565, -0.06437805,  0.34490234, -0.08008734]])

In [62]:
# Create an array with 10 evenly spaced numbers between 1 and 100
randomly_spaced = np.linspace(1,100,10)
randomly_spaced

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])